version: '3.9'

services:

  appserver:
    container_name: golang-docker-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/golang-docker
    depends_on:
      - mysql_host
      - redis_host

  mysql_host:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: yaTrivoga
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "33066:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  #      - ./:/docker-entrypoint-initdb.d

  redis_host:
    image: redis:latest
    container_name: redis-global
    restart: always
    ports:
      - "63799:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

